apiVersion: apps/v1
kind: Deployment
metadata:
  name: snacktrack-deployment
  labels:
    app: snacktrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snacktrack
  template:
    metadata:
      labels:
        app: snacktrack
    spec:
      containers:
      - name: snacktrack
        image: gcr.io/seraphic-spider-363215/microservice-app-template-snacktrack:latest
        ports:
        - containerPort: 80
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"