apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  labels:
    app: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload
        image: gcr.io/seraphic-spider-363215/microservice-app-template-upload:latest
        ports:
        - containerPort: 80
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"